# Generated by Django 5.2.17 on 2026-09-07 22:23

import apps.orders.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0003_lessonprogress"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="کاربر همین عبارت را وارد می\u200cکند. بزرگی و کوچکی حروف مهم نیست.",
                        max_length=40,
                        unique=True,
                        verbose_name="کد تخفیف",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="توضیح داخلی"
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percent", "درصدی"), ("fixed", "مبلغ ثابت")],
                        default="percent",
                        max_length=10,
                        verbose_name="نوع تخفیف",
                    ),
                ),
                (
                    "value",
                    models.PositiveIntegerField(
                        help_text="برای تخفیف درصدی عددی بین ۱ تا ۱۰۰، و برای مبلغ ثابت، مبلغ به تومان.",
                        verbose_name="مقدار",
                    ),
                ),
                (
                    "max_discount_amount",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="فقط برای تخفیف درصدی. خالی یعنی بدون سقف.",
                        null=True,
                        verbose_name="سقف تخفیف (تومان)",
                    ),
                ),
                (
                    "min_order_amount",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="اگر جمع سبد کمتر از این مبلغ باشد، کد اعمال نمی\u200cشود.",
                        verbose_name="حداقل مبلغ سفارش (تومان)",
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="معتبر از"
                    ),
                ),
                (
                    "valid_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="معتبر تا"
                    ),
                ),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="خالی یعنی نامحدود.",
                        null=True,
                        verbose_name="حداکثر تعداد استفاده",
                    ),
                ),
                (
                    "used_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="تعداد استفاده\u200cشده"
                    ),
                ),
                (
                    "per_user_limit",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="صفر یعنی نامحدود.",
                        verbose_name="حداکثر استفاده هر کاربر",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "courses",
                    models.ManyToManyField(
                        blank=True,
                        help_text="خالی بگذارید تا برای همه دوره\u200cها معتبر باشد.",
                        related_name="coupons",
                        to="courses.course",
                        verbose_name="محدود به دوره\u200cهای",
                    ),
                ),
            ],
            options={
                "verbose_name": "کد تخفیف",
                "verbose_name_plural": "کدهای تخفیف",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        default=apps.orders.models.generate_order_number,
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="شماره سفارش",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار پرداخت"),
                            ("paid", "پرداخت شده"),
                            ("failed", "پرداخت ناموفق"),
                            ("canceled", "لغو شده"),
                            ("refunded", "بازگشت وجه"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "subtotal",
                    models.PositiveIntegerField(default=0, verbose_name="جمع اقلام"),
                ),
                (
                    "discount_amount",
                    models.PositiveIntegerField(default=0, verbose_name="مبلغ تخفیف"),
                ),
                (
                    "total",
                    models.PositiveIntegerField(
                        default=0, verbose_name="مبلغ قابل پرداخت"
                    ),
                ),
                (
                    "coupon_code",
                    models.CharField(
                        blank=True,
                        help_text="عکس متن کد در لحظه ثبت سفارش؛ حتی اگر بعداً کد حذف شود باقی می\u200cماند.",
                        max_length=40,
                        verbose_name="کد تخفیف واردشده",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="نام خریدار"
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="شماره تماس"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="یادداشت خریدار")),
                (
                    "admin_note",
                    models.TextField(blank=True, verbose_name="یادداشت داخلی"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ثبت"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین تغییر"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان پرداخت"
                    ),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="orders.coupon",
                        verbose_name="کد تخفیف",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "سفارش",
                "verbose_name_plural": "سفارش\u200cها",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200, verbose_name="عنوان دوره (در لحظه خرید)"
                    ),
                ),
                ("unit_price", models.PositiveIntegerField(verbose_name="قیمت اصلی")),
                (
                    "final_price",
                    models.PositiveIntegerField(verbose_name="قیمت پرداختی"),
                ),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(default=1, verbose_name="تعداد"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="courses.course",
                        verbose_name="دوره",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                        verbose_name="سفارش",
                    ),
                ),
            ],
            options={
                "verbose_name": "قلم سفارش",
                "verbose_name_plural": "اقلام سفارش",
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["user", "-created_at"], name="orders_orde_user_id_0ae59f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["status"], name="orders_orde_status_c6dd84_idx"),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.UniqueConstraint(
                fields=("order", "course"), name="unique_course_per_order"
            ),
        ),
    ]
