# Generated by Django 5.2.17 on 2026-09-07 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gateway",
                    models.CharField(
                        default="mock", max_length=30, verbose_name="درگاه"
                    ),
                ),
                ("amount", models.PositiveIntegerField(verbose_name="مبلغ (تومان)")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار پرداخت"),
                            ("success", "موفق"),
                            ("failed", "ناموفق"),
                            ("canceled", "انصراف کاربر"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "authority",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="کدی که درگاه هنگام شروع پرداخت می\u200cدهد و در بازگشت با آن شناسایی می\u200cشود.",
                        max_length=100,
                        verbose_name="شناسه تراکنش درگاه",
                    ),
                ),
                (
                    "ref_id",
                    models.CharField(
                        blank=True,
                        help_text="فقط بعد از تأیید موفق پرداخت پر می\u200cشود.",
                        max_length=100,
                        verbose_name="شماره پیگیری بانک",
                    ),
                ),
                (
                    "card_pan",
                    models.CharField(
                        blank=True,
                        help_text="هرگز شماره کامل کارت ذخیره نمی\u200cشود.",
                        max_length=20,
                        verbose_name="چهار رقم آخر کارت",
                    ),
                ),
                (
                    "error_code",
                    models.CharField(blank=True, max_length=50, verbose_name="کد خطا"),
                ),
                (
                    "error_message",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="پیام خطا"
                    ),
                ),
                (
                    "raw_response",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="پاسخ درگاه"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان شروع"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین تغییر"),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان تأیید"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="orders.order",
                        verbose_name="سفارش",
                    ),
                ),
            ],
            options={
                "verbose_name": "تراکنش پرداخت",
                "verbose_name_plural": "تراکنش\u200cهای پرداخت",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["order", "-created_at"],
                        name="orders_paym_order_i_ee6c4b_idx",
                    )
                ],
            },
        ),
    ]
