# Generated by Django 5.2.17 on 2026-10-04 23:36

import apps.courses.storages
import apps.orders.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_payment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CardTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(
                        help_text="اگر مبلغ سفارش بعداً عوض شود، تأیید انجام نمی\u200cشود.",
                        verbose_name="مبلغ سفارش در لحظه ارسال رسید (تومان)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "در انتظار بررسی"),
                            ("approved", "تأیید شده"),
                            ("rejected", "رد شده"),
                        ],
                        db_index=True,
                        default="submitted",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "payer_card_last4",
                    models.CharField(
                        max_length=4, verbose_name="چهار رقم آخر کارت پرداخت\u200cکننده"
                    ),
                ),
                (
                    "tracking_code",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="شماره پیگیری / مرجع"
                    ),
                ),
                (
                    "payer_note",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="توضیح خریدار"
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان بررسی"
                    ),
                ),
                (
                    "reject_reason",
                    models.CharField(
                        blank=True,
                        help_text="برای خریدار نمایش داده و پیامک می\u200cشود.",
                        max_length=300,
                        verbose_name="دلیل رد",
                    ),
                ),
                (
                    "receipts_deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان پاک شدن عکس رسید"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="زمان ارسال رسید"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین تغییر"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="card_transfers",
                        to="orders.order",
                        verbose_name="سفارش",
                    ),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="card_transfer",
                        to="orders.payment",
                        verbose_name="تراکنش ثبت\u200cشده",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="بررسی\u200cکننده",
                    ),
                ),
            ],
            options={
                "verbose_name": "پرداخت کارت به کارت",
                "verbose_name_plural": "پرداخت\u200cهای کارت به کارت",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CardTransferReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        storage=apps.courses.storages.ProtectedStorage(),
                        upload_to=apps.orders.models.card_receipt_path,
                        verbose_name="عکس رسید",
                    ),
                ),
                (
                    "size_bytes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="حجم پس از فشرده\u200cسازی (بایت)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ارسال"),
                ),
                (
                    "transfer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipts",
                        to="orders.cardtransfer",
                        verbose_name="پرداخت",
                    ),
                ),
            ],
            options={
                "verbose_name": "عکس رسید",
                "verbose_name_plural": "عکس\u200cهای رسید",
                "ordering": ["pk"],
            },
        ),
        migrations.AddConstraint(
            model_name="cardtransfer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "submitted")),
                fields=("order",),
                name="one_pending_card_transfer_per_order",
            ),
        ),
    ]
