# Generated by Django 5.2.17 on 2026-08-15 00:39

import apps.accounts.managers
import apps.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        help_text="شماره موبایل به شکل 09xxxxxxxxx — همین شماره نام کاربری شماست.",
                        max_length=11,
                        unique=True,
                        validators=[apps.accounts.validators.validate_iranian_mobile],
                        verbose_name="شماره موبایل",
                    ),
                ),
                (
                    "national_code",
                    models.CharField(
                        blank=True,
                        help_text="تا زمان تکمیل احراز هویت می\u200cتواند خالی باشد.",
                        max_length=10,
                        null=True,
                        unique=True,
                        validators=[apps.accounts.validators.validate_national_code],
                        verbose_name="کد ملی",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=50, verbose_name="نام"),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="نام خانوادگی"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="ایمیل"),
                ),
                (
                    "is_mobile_verified",
                    models.BooleanField(
                        default=False,
                        help_text="بعد از تأیید موفق کد پیامکی True می\u200cشود.",
                        verbose_name="موبایل تأیید شده",
                    ),
                ),
                (
                    "is_identity_verified",
                    models.BooleanField(
                        default=False,
                        help_text="بعد از تطبیق موفق شماره موبایل و کد ملی True می\u200cشود.",
                        verbose_name="هویت تأیید شده",
                    ),
                ),
                (
                    "is_vip",
                    models.BooleanField(default=False, verbose_name="کاربر ویژه"),
                ),
                (
                    "vip_expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="انقضای اشتراک ویژه"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("super_admin", "مدیر ارشد"),
                            ("admin", "مدیر"),
                            ("instructor", "مدرس"),
                            ("student", "دانشجو"),
                            ("finance", "مالی"),
                            ("support", "پشتیبانی"),
                            ("content_manager", "مدیر محتوا"),
                        ],
                        default="student",
                        max_length=20,
                        verbose_name="نقش",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="اگر فعال باشد، کاربر می\u200cتواند وارد پنل مدیریت شود.",
                        verbose_name="دسترسی به پنل مدیریت",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ ثبت\u200cنام"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "کاربر",
                "verbose_name_plural": "کاربران",
                "ordering": ["-created_at"],
            },
            managers=[
                ("objects", apps.accounts.managers.UserManager()),
            ],
        ),
    ]
