# Generated by Django 5.2.17 on 2026-08-25 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstructorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(max_length=120, verbose_name="نام نمایشی"),
                ),
                (
                    "specialty",
                    models.CharField(
                        blank=True,
                        help_text="مثلاً «کارشناس ارشد HSE، مدرس ارزیابی ریسک»",
                        max_length=150,
                        verbose_name="تخصص",
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="بیوگرافی")),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="instructors/",
                        verbose_name="عکس",
                    ),
                ),
                ("linkedin_url", models.URLField(blank=True, verbose_name="لینکدین")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "show_on_homepage",
                    models.BooleanField(
                        default=True, verbose_name="نمایش در صفحه اصلی"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="اگر مدرس حساب کاربری دارد، اینجا وصل کنید.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instructor_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "مدرس",
                "verbose_name_plural": "مدرسان",
                "ordering": ["order", "display_name"],
            },
        ),
    ]
