# Generated by Django 5.2.17 on 2026-09-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_instructorprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="OtpCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        db_index=True, max_length=11, verbose_name="شماره موبایل"
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("register", "ثبت\u200cنام"),
                            ("password_reset", "بازیابی رمز عبور"),
                            ("verify_mobile", "تأیید شماره موبایل"),
                        ],
                        max_length=20,
                        verbose_name="هدف",
                    ),
                ),
                (
                    "code_hash",
                    models.CharField(
                        help_text="کد خام ذخیره نمی\u200cشود؛ فقط نسخه رمزنگاری\u200cشده آن.",
                        max_length=128,
                        verbose_name="اثر انگشت کد",
                    ),
                ),
                (
                    "attempts",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="تعداد تلاش برای تأیید"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ارسال"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="زمان انقضا")),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان استفاده"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="آدرس IP"
                    ),
                ),
            ],
            options={
                "verbose_name": "کد یکبارمصرف",
                "verbose_name_plural": "کدهای یکبارمصرف",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["mobile", "purpose", "-created_at"],
                        name="accounts_ot_mobile_6b39ec_idx",
                    )
                ],
            },
        ),
    ]
