# Generated by Django 5.2.17 on 2026-09-04 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_otpcode"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdentityVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        db_index=True, max_length=11, verbose_name="شماره موبایل"
                    ),
                ),
                (
                    "national_code",
                    models.CharField(max_length=10, verbose_name="کد ملی"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("matched", "تطبیق داشت"),
                            ("not_matched", "تطبیق نداشت"),
                            ("failed", "خطای سرویس"),
                        ],
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "provider",
                    models.CharField(max_length=50, verbose_name="سرویس\u200cدهنده"),
                ),
                (
                    "tracking_code",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="کد رهگیری"
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="پیام سرویس"
                    ),
                ),
                (
                    "raw_response",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="برای پیگیری فنی با ارائه\u200cدهنده سرویس نگه داشته می\u200cشود.",
                        verbose_name="پاسخ خام سرویس",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="آدرس IP"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="زمان استعلام"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="هنگام ثبت\u200cنام هنوز کاربری ساخته نشده، پس می\u200cتواند خالی باشد.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identity_verifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "استعلام هویت",
                "verbose_name_plural": "استعلام\u200cهای هویت",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["mobile", "-created_at"],
                        name="accounts_id_mobile_2ef839_idx",
                    ),
                    models.Index(
                        fields=["status"], name="accounts_id_status_c3533d_idx"
                    ),
                ],
            },
        ),
    ]
