# Generated by Django 5.2.17 on 2026-09-19 00:02

import apps.certificates.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0005_onlinesession"),
        ("exams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_code",
                    models.CharField(
                        help_text="کدی که روی گواهی چاپ می\u200cشود و کاربر آن را می\u200cبیند.",
                        max_length=30,
                        unique=True,
                        verbose_name="کد گواهی",
                    ),
                ),
                (
                    "verification_token",
                    models.CharField(
                        default=apps.certificates.models.generate_verification_token,
                        help_text="آدرس داخل QR روی همین ساخته می\u200cشود، نه روی کد گواهی.",
                        max_length=64,
                        unique=True,
                        verbose_name="توکن استعلام",
                    ),
                ),
                (
                    "holder_name",
                    models.CharField(max_length=150, verbose_name="نام دارنده"),
                ),
                (
                    "course_title",
                    models.CharField(max_length=200, verbose_name="عنوان دوره"),
                ),
                (
                    "course_hours",
                    models.PositiveIntegerField(
                        default=0, verbose_name="مدت دوره (ساعت)"
                    ),
                ),
                (
                    "instructor_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="نام مدرس"
                    ),
                ),
                (
                    "score",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="خالی یعنی دوره آزمون نداشته.",
                        null=True,
                        verbose_name="نمره آزمون",
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاریخ صدور"
                    ),
                ),
                (
                    "valid_until",
                    models.DateField(
                        blank=True,
                        help_text="خالی یعنی گواهی تاریخ انقضا ندارد.",
                        null=True,
                        verbose_name="اعتبار تا",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "معتبر"), ("revoked", "باطل\u200cشده")],
                        default="active",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "revoke_reason",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="علت ابطال"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین تغییر"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="certificates",
                        to="courses.course",
                        verbose_name="دوره",
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certificates",
                        to="courses.enrollment",
                        verbose_name="ثبت\u200cنام",
                    ),
                ),
                (
                    "exam_attempt",
                    models.ForeignKey(
                        blank=True,
                        help_text="اگر دوره آزمون داشته، کارنامه\u200cای که مبنای صدور بوده.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certificates",
                        to="exams.examattempt",
                        verbose_name="کارنامه آزمون",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="دانشجو",
                    ),
                ),
            ],
            options={
                "verbose_name": "گواهی",
                "verbose_name_plural": "گواهی\u200cها",
                "ordering": ["-issued_at"],
                "indexes": [
                    models.Index(
                        fields=["certificate_code"],
                        name="certificate_certifi_0d7e7f_idx",
                    ),
                    models.Index(
                        fields=["user", "status"], name="certificate_user_id_42f10a_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "course"),
                        name="unique_certificate_per_user_course",
                    )
                ],
            },
        ),
    ]
