# Generated by Django 5.2.17 on 2026-08-18 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="اگر خاموش باشد، در سایت نمایش داده نمی\u200cشود.",
                        verbose_name="فعال",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="عدد کوچک\u200cتر بالاتر نمایش داده می\u200cشود.",
                        verbose_name="ترتیب نمایش",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="متن کوتاه بالای عنوان، مثل «دوره ویژه این ماه»",
                        max_length=50,
                        verbose_name="برچسب کوچک",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="عنوان بنر")),
                ("subtitle", models.TextField(blank=True, verbose_name="توضیح کوتاه")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="banners/",
                        verbose_name="تصویر بنر",
                    ),
                ),
                (
                    "cta_text",
                    models.CharField(
                        blank=True,
                        default="مشاهده دوره",
                        max_length=50,
                        verbose_name="متن دکمه",
                    ),
                ),
                (
                    "cta_url",
                    models.CharField(
                        blank=True,
                        help_text="مثلاً /courses/hse-officer/",
                        max_length=300,
                        verbose_name="لینک دکمه",
                    ),
                ),
                (
                    "date_text",
                    models.CharField(
                        blank=True,
                        help_text="مثلاً «شروع: ۱۵ مهر ۱۴۰۴»",
                        max_length=100,
                        verbose_name="متن تاریخ",
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="خالی یعنی بدون محدودیت شروع.",
                        null=True,
                        verbose_name="نمایش از تاریخ",
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="خالی یعنی بدون محدودیت پایان.",
                        null=True,
                        verbose_name="نمایش تا تاریخ",
                    ),
                ),
            ],
            options={
                "verbose_name": "بنر",
                "verbose_name_plural": "بنرها",
                "ordering": ["order", "-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=100, verbose_name="نام و نام خانوادگی"),
                ),
                ("mobile", models.CharField(max_length=20, verbose_name="شماره تماس")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="ایمیل"),
                ),
                ("subject", models.CharField(max_length=150, verbose_name="موضوع")),
                ("message", models.TextField(verbose_name="متن پیام")),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="خوانده شده"),
                ),
                (
                    "admin_note",
                    models.TextField(blank=True, verbose_name="یادداشت داخلی"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ارسال"),
                ),
            ],
            options={
                "verbose_name": "پیام تماس",
                "verbose_name_plural": "پیام\u200cهای تماس",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="اگر خاموش باشد، در سایت نمایش داده نمی\u200cشود.",
                        verbose_name="فعال",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="عدد کوچک\u200cتر بالاتر نمایش داده می\u200cشود.",
                        verbose_name="ترتیب نمایش",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
                ("question", models.CharField(max_length=250, verbose_name="سؤال")),
                ("answer", models.TextField(verbose_name="پاسخ")),
                (
                    "show_on_homepage",
                    models.BooleanField(
                        default=True,
                        help_text="اگر خاموش باشد فقط در صفحه سؤالات متداول دیده می\u200cشود.",
                        verbose_name="نمایش در صفحه اصلی",
                    ),
                ),
            ],
            options={
                "verbose_name": "سؤال متداول",
                "verbose_name_plural": "سؤالات متداول",
                "ordering": ["order", "-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="اگر خاموش باشد، در سایت نمایش داده نمی\u200cشود.",
                        verbose_name="فعال",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="عدد کوچک\u200cتر بالاتر نمایش داده می\u200cشود.",
                        verbose_name="ترتیب نمایش",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("shield", "سپر ایمنی"),
                            ("certificate", "گواهی"),
                            ("users", "مدرسان"),
                            ("video", "کلاس آنلاین"),
                            ("download", "محتوای آفلاین"),
                            ("lock", "پرداخت امن"),
                            ("headset", "پشتیبانی"),
                            ("chart", "کاربردی"),
                        ],
                        default="shield",
                        max_length=20,
                        verbose_name="آیکون",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="عنوان")),
                ("description", models.TextField(blank=True, verbose_name="توضیح")),
            ],
            options={
                "verbose_name": "مزیت (چرا ما)",
                "verbose_name_plural": "مزیت\u200cها (چرا ما)",
                "ordering": ["order", "-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="اگر خاموش باشد، در سایت نمایش داده نمی\u200cشود.",
                        verbose_name="فعال",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="عدد کوچک\u200cتر بالاتر نمایش داده می\u200cشود.",
                        verbose_name="ترتیب نمایش",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
                ("name", models.CharField(max_length=120, verbose_name="نام سازمان")),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="partners/",
                        verbose_name="لوگو",
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="وب\u200cسایت")),
            ],
            options={
                "verbose_name": "همکار",
                "verbose_name_plural": "سازمان\u200cهای همکار",
                "ordering": ["order", "-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SiteSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="آکادمی HSE", max_length=100, verbose_name="نام سایت"
                    ),
                ),
                (
                    "site_tagline",
                    models.CharField(
                        blank=True,
                        default="آموزش تخصصی ایمنی، بهداشت و محیط زیست",
                        max_length=200,
                        verbose_name="شعار سایت",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="site/", verbose_name="لوگو"
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="site/",
                        verbose_name="آیکون مرورگر",
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(
                        default="آموزش تخصصی HSE با گواهی معتبر و قابل استعلام",
                        max_length=200,
                        verbose_name="عنوان اصلی صفحه نخست",
                    ),
                ),
                (
                    "hero_subtitle",
                    models.TextField(
                        blank=True,
                        default="دوره\u200cهای کاربردی ایمنی، بهداشت حرفه\u200cای و محیط زیست، زیر نظر مدرسان صنعت و متناسب با نیاز واقعی سازمان\u200cها.",
                        verbose_name="زیرعنوان صفحه نخست",
                    ),
                ),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="site/",
                        verbose_name="تصویر صفحه نخست",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        default="021-00000000",
                        max_length=30,
                        verbose_name="تلفن تماس",
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="موبایل پشتیبانی"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default="info@example.com",
                        max_length=254,
                        verbose_name="ایمیل",
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="آدرس")),
                (
                    "working_hours",
                    models.CharField(
                        blank=True,
                        default="شنبه تا چهارشنبه، ۹ تا ۱۷",
                        max_length=120,
                        verbose_name="ساعات کاری",
                    ),
                ),
                (
                    "instagram_url",
                    models.URLField(blank=True, verbose_name="اینستاگرام"),
                ),
                ("telegram_url", models.URLField(blank=True, verbose_name="تلگرام")),
                ("linkedin_url", models.URLField(blank=True, verbose_name="لینکدین")),
                ("whatsapp_url", models.URLField(blank=True, verbose_name="واتساپ")),
                (
                    "about_short",
                    models.TextField(
                        blank=True,
                        default="آکادمی تخصصی آموزش ایمنی، بهداشت و محیط زیست.",
                        verbose_name="معرفی کوتاه (فوتر)",
                    ),
                ),
                (
                    "about_full",
                    models.TextField(blank=True, verbose_name="متن کامل درباره ما"),
                ),
                (
                    "show_categories_section",
                    models.BooleanField(
                        default=True, verbose_name="نمایش بخش دسته\u200cبندی\u200cها"
                    ),
                ),
                (
                    "show_banner_section",
                    models.BooleanField(default=True, verbose_name="نمایش بنر ماهانه"),
                ),
                (
                    "show_featured_courses",
                    models.BooleanField(
                        default=True, verbose_name="نمایش دوره\u200cهای منتخب"
                    ),
                ),
                (
                    "show_upcoming_courses",
                    models.BooleanField(
                        default=True, verbose_name="نمایش دوره\u200cهای پیش\u200cرو"
                    ),
                ),
                (
                    "show_features_section",
                    models.BooleanField(default=True, verbose_name="نمایش بخش چرا ما"),
                ),
                (
                    "show_certificate_cta",
                    models.BooleanField(
                        default=True, verbose_name="نمایش استعلام گواهی"
                    ),
                ),
                (
                    "show_instructors_section",
                    models.BooleanField(default=True, verbose_name="نمایش مدرسان"),
                ),
                (
                    "show_testimonials_section",
                    models.BooleanField(default=True, verbose_name="نمایش نظرات"),
                ),
                (
                    "show_partners_section",
                    models.BooleanField(default=True, verbose_name="نمایش همکاران"),
                ),
                (
                    "show_faq_section",
                    models.BooleanField(
                        default=True, verbose_name="نمایش سؤالات متداول"
                    ),
                ),
                (
                    "show_articles_section",
                    models.BooleanField(
                        default=False,
                        help_text="بخش مقالات در نسخه اول منتشر نمی\u200cشود.",
                        verbose_name="نمایش مقالات",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=70, verbose_name="عنوان سئو"
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="توضیحات سئو"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "تنظیمات سایت",
                "verbose_name_plural": "تنظیمات سایت",
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="اگر خاموش باشد، در سایت نمایش داده نمی\u200cشود.",
                        verbose_name="فعال",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="عدد کوچک\u200cتر بالاتر نمایش داده می\u200cشود.",
                        verbose_name="ترتیب نمایش",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
                (
                    "full_name",
                    models.CharField(max_length=100, verbose_name="نام و نام خانوادگی"),
                ),
                (
                    "job_title",
                    models.CharField(
                        blank=True,
                        help_text="مثلاً «کارشناس HSE، شرکت پتروشیمی»",
                        max_length=120,
                        verbose_name="سمت یا سازمان",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="testimonials/",
                        verbose_name="عکس",
                    ),
                ),
                ("quote", models.TextField(verbose_name="متن نظر")),
            ],
            options={
                "verbose_name": "نظر دانشجو",
                "verbose_name_plural": "نظرات دانشجویان",
                "ordering": ["order", "-created_at"],
                "abstract": False,
            },
        ),
    ]
