# Generated by Django 5.2.17 on 2026-08-25 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="اگر خاموش باشد، در سایت نمایش داده نمی\u200cشود.",
                        verbose_name="فعال",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="عدد کوچک\u200cتر بالاتر نمایش داده می\u200cشود.",
                        verbose_name="ترتیب نمایش",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="روی تصویر نمایش داده نمی\u200cشود.",
                        max_length=150,
                        verbose_name="عنوان (فقط برای پنل و متن جایگزین تصویر)",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="اندازه پیشنهادی: ۱۹۲۰×۶۵۰ پیکسل.",
                        upload_to="slides/",
                        verbose_name="تصویر اسلاید",
                    ),
                ),
                (
                    "image_mobile",
                    models.ImageField(
                        blank=True,
                        help_text="اختیاری. اگر خالی باشد، همان تصویر اصلی استفاده می\u200cشود.",
                        null=True,
                        upload_to="slides/",
                        verbose_name="تصویر نسخه موبایل",
                    ),
                ),
                (
                    "link_url",
                    models.CharField(
                        blank=True,
                        help_text="با کلیک روی تصویر کاربر به این آدرس می\u200cرود. خالی یعنی بدون لینک.",
                        max_length=300,
                        verbose_name="لینک اسلاید",
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="خالی یعنی بدون محدودیت شروع.",
                        null=True,
                        verbose_name="نمایش از تاریخ",
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="خالی یعنی بدون محدودیت پایان.",
                        null=True,
                        verbose_name="نمایش تا تاریخ",
                    ),
                ),
            ],
            options={
                "verbose_name": "اسلاید صفحه اصلی",
                "verbose_name_plural": "اسلایدهای صفحه اصلی",
                "ordering": ["order", "-created_at"],
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="Banner",
        ),
        migrations.RemoveField(
            model_name="sitesetting",
            name="hero_image",
        ),
        migrations.RemoveField(
            model_name="sitesetting",
            name="hero_subtitle",
        ),
        migrations.RemoveField(
            model_name="sitesetting",
            name="hero_title",
        ),
        migrations.RemoveField(
            model_name="sitesetting",
            name="show_banner_section",
        ),
        migrations.RemoveField(
            model_name="sitesetting",
            name="show_certificate_cta",
        ),
        migrations.RemoveField(
            model_name="sitesetting",
            name="show_upcoming_courses",
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="homepage_calendar_count",
            field=models.PositiveIntegerField(
                default=6, verbose_name="تعداد ردیف تقویم آموزشی در صفحه اصلی"
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="homepage_category_count",
            field=models.PositiveIntegerField(
                default=8, verbose_name="تعداد دسته\u200cبندی در صفحه اصلی"
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="show_calendar_section",
            field=models.BooleanField(
                default=True, verbose_name="نمایش تقویم دوره\u200cهای آموزشی"
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="show_hero_slider",
            field=models.BooleanField(
                default=True, verbose_name="نمایش اسلایدر بالای صفحه"
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="site_name",
            field=models.CharField(
                default="HSE Tech", max_length=100, verbose_name="نام سایت"
            ),
        ),
    ]
