# Generated by Django 5.2.17 on 2026-08-25 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_heroslide_delete_banner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesetting",
            name="hero_slider_interval_seconds",
            field=models.PositiveIntegerField(
                default=6,
                help_text="هر چند ثانیه یک\u200cبار اسلاید بعدی نمایش داده شود.",
                verbose_name="فاصله بین اسلایدها (ثانیه)",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="hero_slider_transition_ms",
            field=models.PositiveIntegerField(
                default=1100,
                help_text="عدد بزرگ\u200cتر یعنی جابه\u200cجایی نرم\u200cتر و کندتر. مقدار پیشنهادی بین ۸۰۰ تا ۱۵۰۰.",
                verbose_name="مدت محو شدن اسلاید (میلی\u200cثانیه)",
            ),
        ),
    ]
