# Generated by Django 5.2.17 on 2026-08-25 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_sitesetting_hero_slider_interval_seconds_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesetting",
            name="hero_slider_transition_ms",
            field=models.PositiveIntegerField(
                default=1400,
                help_text="عدد بزرگ\u200cتر یعنی جابه\u200cجایی نرم\u200cتر و کندتر. مقدار پیشنهادی بین ۸۰۰ تا ۱۵۰۰.",
                verbose_name="مدت محو شدن اسلاید (میلی\u200cثانیه)",
            ),
        ),
    ]
