# Generated by Django 5.2.17 on 2026-10-04 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_sitesetting_hero_slider_transition_ms"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesetting",
            name="card_transfer_bank",
            field=models.CharField(blank=True, max_length=50, verbose_name="نام بانک"),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="card_transfer_enabled",
            field=models.BooleanField(
                default=False,
                help_text="تا شماره کارت وارد نشده باشد، این گزینه به خریدار نمایش داده نمی\u200cشود.",
                verbose_name="فعال بودن پرداخت کارت به کارت",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="card_transfer_holder",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="نام صاحب کارت"
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="card_transfer_note",
            field=models.TextField(
                blank=True,
                help_text="زیر اطلاعات کارت نمایش داده می\u200cشود.",
                verbose_name="توضیح برای خریدار (اختیاری)",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="card_transfer_notify_mobile",
            field=models.CharField(
                blank=True,
                help_text="با ثبت هر رسید، به این شماره پیامک می\u200cرود. خالی یعنی پیامک نرود.",
                max_length=11,
                verbose_name="موبایل مدیر برای اطلاع از رسید جدید",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="card_transfer_number",
            field=models.CharField(
                blank=True,
                help_text="۱۶ رقم؛ با یا بدون فاصله.",
                max_length=19,
                verbose_name="شماره کارت مقصد",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="card_transfer_sheba",
            field=models.CharField(
                blank=True,
                help_text="برای مبالغ بیشتر از سقف کارت به کارت. مثال: IR000000000000000000000000",
                max_length=34,
                verbose_name="شماره شبا (اختیاری)",
            ),
        ),
    ]
