# Generated by Django 5.2.17 on 2026-08-25 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_instructorprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="نام دسته\u200cبندی"),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        help_text="در آدرس صفحه استفاده می\u200cشود. مثال: risk-assessment",
                        max_length=120,
                        unique=True,
                        verbose_name="نشانی یکتا (اسلاگ)",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="توضیح کوتاه"),
                ),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("shield", "سپر ایمنی"),
                            ("chart", "ارزیابی و تحلیل"),
                            ("users", "منابع انسانی"),
                            ("certificate", "استاندارد و گواهی"),
                            ("video", "آموزش آنلاین"),
                            ("book", "آموزش عمومی"),
                            ("lock", "کنترل و بازرسی"),
                            ("headset", "پشتیبانی و مدیریت"),
                        ],
                        default="shield",
                        max_length=20,
                        verbose_name="آیکون",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="categories/",
                        verbose_name="تصویر",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "show_on_homepage",
                    models.BooleanField(
                        default=True,
                        help_text="فقط چند دسته منتخب در صفحه اصلی نمایش داده می\u200cشوند.",
                        verbose_name="نمایش در صفحه اصلی",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=70, verbose_name="عنوان سئو"
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="توضیحات سئو"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="برای ساخت زیردسته. برای دسته اصلی خالی بگذارید.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="courses.coursecategory",
                        verbose_name="دسته\u200cبندی والد",
                    ),
                ),
            ],
            options={
                "verbose_name": "دسته\u200cبندی دوره",
                "verbose_name_plural": "دسته\u200cبندی دوره\u200cها",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان دوره")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        help_text="در آدرس دوره استفاده می\u200cشود. مثال: hse-officer",
                        max_length=220,
                        unique=True,
                        verbose_name="نشانی یکتا (اسلاگ)",
                    ),
                ),
                (
                    "short_description",
                    models.TextField(
                        blank=True,
                        help_text="روی کارت دوره نمایش داده می\u200cشود.",
                        max_length=300,
                        verbose_name="توضیح کوتاه",
                    ),
                ),
                (
                    "full_description",
                    models.TextField(blank=True, verbose_name="توضیح کامل"),
                ),
                (
                    "course_type",
                    models.CharField(
                        choices=[
                            ("online_live", "آنلاین زنده"),
                            ("offline_recorded", "آفلاین (ضبط\u200cشده)"),
                            ("hybrid", "ترکیبی"),
                        ],
                        default="online_live",
                        max_length=20,
                        verbose_name="شیوه برگزاری",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("beginner", "مقدماتی"),
                            ("intermediate", "متوسط"),
                            ("advanced", "پیشرفته"),
                        ],
                        default="beginner",
                        max_length=20,
                        verbose_name="سطح",
                    ),
                ),
                (
                    "price",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="صفر یعنی دوره رایگان است.",
                        verbose_name="قیمت (تومان)",
                    ),
                ),
                (
                    "discount_price",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="اگر پر شود، قیمت اصلی خط\u200cخورده نمایش داده می\u200cشود.",
                        null=True,
                        verbose_name="قیمت با تخفیف (تومان)",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="courses/",
                        verbose_name="تصویر کارت دوره",
                    ),
                ),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="courses/",
                        verbose_name="تصویر بزرگ دوره",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="تاریخ شروع"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="تاریخ پایان"),
                ),
                (
                    "duration_hours",
                    models.PositiveIntegerField(
                        default=0, verbose_name="مدت دوره (ساعت)"
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="خالی یعنی بدون محدودیت.",
                        null=True,
                        verbose_name="ظرفیت",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="برای دوره\u200cهای آنلاین می\u200cتوانید «آنلاین» بنویسید.",
                        max_length=120,
                        verbose_name="محل برگزاری",
                    ),
                ),
                (
                    "prerequisites",
                    models.TextField(blank=True, verbose_name="پیش\u200cنیازها"),
                ),
                (
                    "target_audience",
                    models.TextField(blank=True, verbose_name="مخاطبان دوره"),
                ),
                (
                    "syllabus",
                    models.TextField(
                        blank=True,
                        help_text="هر سرفصل را در یک خط بنویسید.",
                        verbose_name="سرفصل\u200cها",
                    ),
                ),
                (
                    "certificate_available",
                    models.BooleanField(default=True, verbose_name="دارای گواهی"),
                ),
                (
                    "exam_available",
                    models.BooleanField(default=True, verbose_name="دارای آزمون"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="دوره منتخب"),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="تا وقتی خاموش باشد، دوره در سایت دیده نمی\u200cشود.",
                        verbose_name="منتشر شده",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=70, verbose_name="عنوان سئو"
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="توضیحات سئو"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="courses",
                        to="accounts.instructorprofile",
                        verbose_name="مدرس",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="courses",
                        to="courses.coursecategory",
                        verbose_name="دسته\u200cبندی",
                    ),
                ),
            ],
            options={
                "verbose_name": "دوره",
                "verbose_name_plural": "دوره\u200cها",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_published", "is_featured"],
                        name="courses_cou_is_publ_bc1413_idx",
                    ),
                    models.Index(
                        fields=["start_date"], name="courses_cou_start_d_2c5b9f_idx"
                    ),
                ],
            },
        ),
    ]
