"""ساختار محتوای دوره: فصل‌ها، درس‌ها و پیوست‌های هر درس."""

# Generated by Django 5.2.17 on 2026-09-04 22:10

import apps.courses.storages
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان درس")),
                (
                    "summary",
                    models.TextField(
                        blank=True, max_length=400, verbose_name="توضیح کوتاه"
                    ),
                ),
                (
                    "lesson_type",
                    models.CharField(
                        choices=[
                            ("video", "ویدیو"),
                            ("text", "متن آموزشی"),
                            ("file", "فایل و جزوه"),
                            ("live", "جلسه آنلاین زنده"),
                        ],
                        default="video",
                        max_length=20,
                        verbose_name="نوع محتوا",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="برای درس\u200cهای متنی می\u200cتوانید زمان تقریبی مطالعه را بنویسید.",
                        verbose_name="مدت (دقیقه)",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="برای درس\u200cهای متنی. برای ویدیو می\u200cتوانید خلاصه یا نکات مهم را بنویسید.",
                        verbose_name="متن درس",
                    ),
                ),
                (
                    "video_file",
                    models.FileField(
                        blank=True,
                        help_text="فایل روی سرور خودتان و خارج از دسترس مستقیم ذخیره می\u200cشود.",
                        null=True,
                        storage=apps.courses.storages.ProtectedStorage(),
                        upload_to=apps.courses.storages.lesson_video_path,
                        verbose_name="فایل ویدیو",
                    ),
                ),
                (
                    "video_external_url",
                    models.URLField(
                        blank=True,
                        help_text="اگر ویدیو روی سرور دیگری از خودتان است، آدرس مستقیم فایل را بگذارید. برای پایداری در زمان اختلال اینترنت، از سرویس\u200cهای خارجی استفاده نکنید.",
                        verbose_name="آدرس مستقیم ویدیو",
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="فقط برای جلسه\u200cهای آنلاین زنده.",
                        null=True,
                        verbose_name="زمان برگزاری",
                    ),
                ),
                (
                    "is_free_preview",
                    models.BooleanField(
                        default=False,
                        help_text="اگر روشن باشد، این درس برای همه بازدیدکنندگان باز است.",
                        verbose_name="پیش\u200cنمایش رایگان",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="منتشر شده"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "درس",
                "verbose_name_plural": "درس\u200cها",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="LessonAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان فایل")),
                (
                    "file",
                    models.FileField(
                        storage=apps.courses.storages.ProtectedStorage(),
                        upload_to=apps.courses.storages.lesson_attachment_path,
                        verbose_name="فایل",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ افزودن"
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="courses.lesson",
                        verbose_name="درس",
                    ),
                ),
            ],
            options={
                "verbose_name": "پیوست درس",
                "verbose_name_plural": "پیوست\u200cهای درس",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان فصل")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="توضیح کوتاه"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="تا وقتی خاموش باشد، این فصل و درس\u200cهایش در سایت دیده نمی\u200cشوند.",
                        verbose_name="منتشر شده",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="courses.course",
                        verbose_name="دوره",
                    ),
                ),
            ],
            options={
                "verbose_name": "فصل دوره",
                "verbose_name_plural": "فصل\u200cهای دوره",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="lesson",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="courses.section",
                verbose_name="فصل",
            ),
        ),
        migrations.AddIndex(
            model_name="section",
            index=models.Index(
                fields=["course", "order"], name="courses_sec_course__60bff3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(
                fields=["section", "order"], name="courses_les_section_573283_idx"
            ),
        ),
    ]
