# Generated by Django 5.2.17 on 2026-09-04 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_sections_and_lessons"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="تکمیل شده"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان تکمیل"
                    ),
                ),
                (
                    "last_position_seconds",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="برای ادامه دادن ویدیو از همان جایی که کاربر رها کرده بود.",
                        verbose_name="آخرین ثانیه تماشا",
                    ),
                ),
                (
                    "first_viewed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="اولین بازدید"
                    ),
                ),
                (
                    "last_viewed_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بازدید"),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_records",
                        to="courses.lesson",
                        verbose_name="درس",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_progress",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "پیشرفت درس",
                "verbose_name_plural": "پیشرفت درس\u200cها",
                "ordering": ["-last_viewed_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-last_viewed_at"],
                        name="courses_les_user_id_eb278a_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "lesson"),
                        name="unique_progress_per_user_lesson",
                    )
                ],
            },
        ),
    ]
