"""ثبت‌نام دانشجو در دوره، و مدت دسترسی هر دوره."""

# Generated by Django 5.2.17 on 2026-09-07 23:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_lessonprogress"),
        ("orders", "0002_payment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="access_duration_days",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="بعد از خرید، دانشجو چند روز به محتوای دوره دسترسی داشته باشد؟ خالی بگذارید تا دسترسی دائمی باشد.",
                null=True,
                verbose_name="مدت دسترسی (روز)",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="vip_access",
            field=models.BooleanField(
                default=True,
                help_text="اگر خاموش باشد، این دوره حتی برای کاربران ویژه هم باید جداگانه خریداری شود.",
                verbose_name="در دسترس کاربران ویژه",
            ),
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("purchase", "خرید"),
                            ("free", "دوره رایگان"),
                            ("manual", "افزودن دستی توسط مدیر"),
                            ("vip", "اشتراک ویژه"),
                            ("gift", "هدیه"),
                        ],
                        default="purchase",
                        max_length=20,
                        verbose_name="منبع ثبت\u200cنام",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "فعال"),
                            ("suspended", "تعلیق\u200cشده"),
                            ("refunded", "بازگشت وجه"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="شروع دسترسی"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="خالی یعنی دسترسی دائمی است.",
                        null=True,
                        verbose_name="پایان دسترسی",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="یادداشت"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ ثبت\u200cنام"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین تغییر"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="courses.course",
                        verbose_name="دوره",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        help_text="اگر ثبت\u200cنام از راه خرید بوده، سفارش مربوطه.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enrollments",
                        to="orders.order",
                        verbose_name="سفارش",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "ثبت\u200cنام",
                "verbose_name_plural": "ثبت\u200cنام\u200cها",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="courses_enr_user_id_ce8b5b_idx"
                    ),
                    models.Index(
                        fields=["course", "status"],
                        name="courses_enr_course__78d524_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "course"),
                        name="unique_enrollment_per_user_course",
                    )
                ],
            },
        ),
    ]
