# Generated by Django 5.2.17 on 2026-09-18 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_enrollment"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnlineSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان جلسه")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="توضیح کوتاه"),
                ),
                ("starts_at", models.DateTimeField(verbose_name="زمان شروع")),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(default=90, verbose_name="مدت (دقیقه)"),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        db_index=True, editable=False, verbose_name="زمان پایان"
                    ),
                ),
                (
                    "meeting_url",
                    models.URLField(
                        blank=True,
                        help_text="لینکی که از پنل اسکای\u200cروم کپی می\u200cکنید. این آدرس هرگز در صفحه سایت نمایش داده نمی\u200cشود و فقط به کاربر ثبت\u200cنام\u200cشده تحویل می\u200cشود.",
                        verbose_name="آدرس ورود به کلاس",
                    ),
                ),
                (
                    "room_id",
                    models.CharField(
                        blank=True,
                        help_text="فقط برای حالت اتصال خودکار به API اسکای\u200cروم لازم است.",
                        max_length=50,
                        verbose_name="شناسه کلاس در اسکای\u200cروم",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "برنامه\u200cریزی\u200cشده"),
                            ("cancelled", "لغو شده"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "cancel_reason",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="علت لغو"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="online_sessions",
                        to="courses.course",
                        verbose_name="دوره",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        help_text="اختیاری. اگر این جلسه در سرفصل دوره هم یک درس دارد، آن را انتخاب کنید.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="online_sessions",
                        to="courses.lesson",
                        verbose_name="درس مرتبط",
                    ),
                ),
            ],
            options={
                "verbose_name": "جلسه آنلاین",
                "verbose_name_plural": "جلسه\u200cهای آنلاین",
                "ordering": ["starts_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["course", "starts_at"],
                        name="courses_onl_course__75646a_idx",
                    )
                ],
            },
        ),
    ]
