# Generated by Django 5.2.17 on 2026-09-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_onlinesession"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="completed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="برای دوره حضوری: بعد از اینکه دانشجو در کلاس شرکت کرد و دوره را گذراند، این تاریخ را پر کنید (یا از عملیات «تأیید گذراندن دوره» در فهرست ثبت\u200cنام\u200cها استفاده کنید). تا خالی است، آزمون پایانی (اگر «فقط پس از تکمیل دوره» باشد) و گواهی باز نمی\u200cشوند.",
                null=True,
                verbose_name="تأیید گذراندن دوره",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_type",
            field=models.CharField(
                choices=[
                    ("in_person", "حضوری"),
                    ("online_live", "آنلاین زنده"),
                    ("offline_recorded", "آفلاین (ضبط\u200cشده)"),
                    ("hybrid", "ترکیبی"),
                ],
                default="in_person",
                help_text="تا وقتی دوره\u200cهای غیرحضوری خاموش\u200cاند (ONLINE_COURSES_ENABLED)، دوره\u200cای با شیوه\u200cای غیر از «حضوری» در سایت دیده نمی\u200cشود.",
                max_length=20,
                verbose_name="شیوه برگزاری",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="نشانی یا شهر برگزاری کلاس حضوری. مثال: تهران، خیابان ولیعصر، سالن همایش",
                max_length=120,
                verbose_name="محل برگزاری",
            ),
        ),
    ]
