# Generated by Django 5.2.17 on 2026-09-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_in_person_courses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="capacity",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="خالی یعنی بدون محدودیت. وقتی ظرفیت پر شود، ثبت\u200cنام در سایت خودکار بسته می\u200cشود (ثبت\u200cنام دستی از همین پنل همچنان ممکن است).",
                null=True,
                verbose_name="ظرفیت",
            ),
        ),
    ]
