# Generated by Django 5.2.17 on 2026-09-19 00:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="نام دسته\u200cبندی"),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        help_text="در آدرس صفحه استفاده می\u200cشود. خالی بگذارید تا از روی نام ساخته شود.",
                        max_length=120,
                        unique=True,
                        verbose_name="نامک (آدرس)",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="توضیح کوتاه"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=70, verbose_name="عنوان سئو"
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="توضیحات سئو"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
            ],
            options={
                "verbose_name": "دسته\u200cبندی مقاله",
                "verbose_name_plural": "دسته\u200cبندی\u200cهای مقاله",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        help_text="خالی بگذارید تا از روی عنوان ساخته شود.",
                        max_length=220,
                        unique=True,
                        verbose_name="نامک (آدرس)",
                    ),
                ),
                (
                    "post_type",
                    models.CharField(
                        choices=[("article", "مقاله"), ("news", "خبر")],
                        default="article",
                        max_length=20,
                        verbose_name="نوع مطلب",
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        help_text="در کارت مطلب و نتایج جست\u200cوجو نمایش داده می\u200cشود.",
                        max_length=400,
                        verbose_name="چکیده",
                    ),
                ),
                ("content", models.TextField(verbose_name="متن مطلب")),
                (
                    "cover",
                    models.ImageField(
                        blank=True,
                        help_text="اندازه پیشنهادی ۱۲۰۰×۶۳۰ پیکسل.",
                        null=True,
                        upload_to="blog/",
                        verbose_name="تصویر شاخص",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "پیش\u200cنویس"),
                            ("published", "منتشرشده"),
                            ("archived", "بایگانی\u200cشده"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="تاریخ آینده یعنی مطلب زمان\u200cبندی شده و تا آن لحظه در سایت دیده نمی\u200cشود.",
                        verbose_name="تاریخ انتشار",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="مطلب منتخب"),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=70, verbose_name="عنوان سئو"
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="توضیحات سئو"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین ویرایش"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        help_text="خالی یعنی مطلب به نام خود آکادمی منتشر می\u200cشود.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blog_posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="نویسنده",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posts",
                        to="blog.blogcategory",
                        verbose_name="دسته\u200cبندی",
                    ),
                ),
            ],
            options={
                "verbose_name": "مقاله و خبر",
                "verbose_name_plural": "مقاله\u200cها و خبرها",
                "ordering": ["-published_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["status", "published_at"],
                        name="blog_blogpo_status_aa5436_idx",
                    ),
                    models.Index(
                        fields=["post_type", "status"],
                        name="blog_blogpo_post_ty_c6a5ae_idx",
                    ),
                ],
            },
        ),
    ]
