# Generated by Django 5.2.17 on 2026-09-18 23:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0005_onlinesession"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="آزمون پایان دوره",
                        max_length=200,
                        verbose_name="عنوان آزمون",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="پیش از شروع آزمون به دانشجو نشان داده می\u200cشود.",
                        verbose_name="توضیح و قوانین",
                    ),
                ),
                (
                    "question_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="صفر یعنی همه سؤال\u200cهای فعال. اگر عددی کمتر از تعداد سؤال\u200cها بگذارید، برای هر دانشجو همان تعداد سؤال تصادفی انتخاب می\u200cشود.",
                        verbose_name="تعداد سؤال هر آزمون",
                    ),
                ),
                (
                    "time_limit_minutes",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="صفر یعنی بدون محدودیت زمانی.",
                        verbose_name="مدت آزمون (دقیقه)",
                    ),
                ),
                (
                    "pass_score",
                    models.PositiveIntegerField(
                        default=70,
                        help_text="دانشجو با این درصد یا بالاتر، قبول می\u200cشود.",
                        verbose_name="نمره قبولی (درصد)",
                    ),
                ),
                (
                    "max_attempts",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="صفر یعنی بدون محدودیت.",
                        verbose_name="حداکثر دفعات شرکت",
                    ),
                ),
                (
                    "shuffle_questions",
                    models.BooleanField(
                        default=True, verbose_name="ترتیب تصادفی سؤال\u200cها"
                    ),
                ),
                (
                    "shuffle_options",
                    models.BooleanField(
                        default=True, verbose_name="ترتیب تصادفی گزینه\u200cها"
                    ),
                ),
                (
                    "show_correct_answers",
                    models.BooleanField(
                        default=True,
                        help_text="اگر خاموش باشد، دانشجو فقط نمره\u200cاش را می\u200cبیند.",
                        verbose_name="نمایش پاسخ درست بعد از آزمون",
                    ),
                ),
                (
                    "require_course_completion",
                    models.BooleanField(
                        default=False,
                        help_text="اگر روشن باشد، تا همه درس\u200cها تکمیل نشوند آزمون باز نمی\u200cشود.",
                        verbose_name="نیاز به تکمیل دوره",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="تا وقتی خاموش است، فقط مدیر و مدرس دوره آزمون را می\u200cبینند.",
                        verbose_name="منتشر شده",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
                (
                    "course",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam",
                        to="courses.course",
                        verbose_name="دوره",
                    ),
                ),
            ],
            options={
                "verbose_name": "آزمون",
                "verbose_name_plural": "آزمون\u200cها",
            },
        ),
        migrations.CreateModel(
            name="ExamAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "در حال انجام"),
                            ("finished", "تصحیح\u200cشده"),
                        ],
                        default="in_progress",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="زمان شروع"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="خالی یعنی آزمون بدون زمان است.",
                        null=True,
                        verbose_name="پایان مهلت",
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان تصحیح"
                    ),
                ),
                (
                    "score",
                    models.PositiveIntegerField(default=0, verbose_name="نمره (درصد)"),
                ),
                (
                    "earned_points",
                    models.PositiveIntegerField(
                        default=0, verbose_name="امتیاز کسب\u200cشده"
                    ),
                ),
                (
                    "total_points",
                    models.PositiveIntegerField(default=0, verbose_name="امتیاز کل"),
                ),
                (
                    "pass_score",
                    models.PositiveIntegerField(
                        default=0, verbose_name="نمره قبولی در زمان آزمون"
                    ),
                ),
                ("is_passed", models.BooleanField(default=False, verbose_name="قبول")),
                (
                    "auto_submitted",
                    models.BooleanField(
                        default=False,
                        help_text="یعنی دانشجو خودش ثبت نکرد و آزمون با پایان مهلت بسته شد.",
                        verbose_name="ثبت خودکار (پایان زمان)",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="exams.exam",
                        verbose_name="آزمون",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_attempts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="دانشجو",
                    ),
                ),
            ],
            options={
                "verbose_name": "تلاش آزمون",
                "verbose_name_plural": "تلاش\u200cهای آزمون",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="متن سؤال")),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "چندگزینه\u200cای"),
                            ("essay", "تشریحی (نسخه بعد)"),
                        ],
                        default="multiple_choice",
                        max_length=20,
                        verbose_name="نوع سؤال",
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True,
                        help_text="بعد از آزمون، همراه پاسخ درست به دانشجو نشان داده می\u200cشود.",
                        verbose_name="توضیح پاسخ",
                    ),
                ),
                (
                    "points",
                    models.PositiveIntegerField(default=1, verbose_name="امتیاز"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="سؤالی که دیگر نمی\u200cخواهید پرسیده شود را غیرفعال کنید، نه اینکه پاکش کنید؛ پاک کردنش کارنامه\u200cهای قبلی را بی\u200cمعنی می\u200cکند.",
                        verbose_name="فعال",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="exams.exam",
                        verbose_name="آزمون",
                    ),
                ),
            ],
            options={
                "verbose_name": "سؤال",
                "verbose_name_plural": "سؤال\u200cها",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="QuestionOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=500, verbose_name="متن گزینه")),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="پاسخ درست"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="exams.question",
                        verbose_name="سؤال",
                    ),
                ),
            ],
            options={
                "verbose_name": "گزینه",
                "verbose_name_plural": "گزینه\u200cها",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="UserAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text_answer",
                    models.TextField(
                        blank=True,
                        help_text="برای سؤال\u200cهای تشریحی نسخه\u200cهای بعد.",
                        verbose_name="پاسخ تشریحی",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="ترتیب در برگه"
                    ),
                ),
                (
                    "points",
                    models.PositiveIntegerField(default=1, verbose_name="امتیاز سؤال"),
                ),
                (
                    "earned_points",
                    models.PositiveIntegerField(
                        default=0, verbose_name="امتیاز کسب\u200cشده"
                    ),
                ),
                ("is_correct", models.BooleanField(default=False, verbose_name="درست")),
                (
                    "answered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان پاسخ"
                    ),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="exams.examattempt",
                        verbose_name="تلاش",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_answers",
                        to="exams.question",
                        verbose_name="سؤال",
                    ),
                ),
                (
                    "selected_option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_answers",
                        to="exams.questionoption",
                        verbose_name="گزینه انتخابی",
                    ),
                ),
            ],
            options={
                "verbose_name": "پاسخ دانشجو",
                "verbose_name_plural": "پاسخ\u200cهای دانشجو",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="examattempt",
            index=models.Index(
                fields=["user", "exam"], name="exams_exama_user_id_574733_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="examattempt",
            index=models.Index(
                fields=["exam", "status"], name="exams_exama_exam_id_39972c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["exam", "order"], name="exams_quest_exam_id_4ac027_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="useranswer",
            constraint=models.UniqueConstraint(
                fields=("attempt", "question"), name="unique_answer_per_question"
            ),
        ),
    ]
