# Generated by Django 5.2.17 on 2026-09-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="require_course_completion",
            field=models.BooleanField(
                default=False,
                help_text="اگر روشن باشد، تا همه درس\u200cها تکمیل نشوند آزمون باز نمی\u200cشود. برای دوره حضوری یعنی: تا آکادمی گذراندن دوره را تأیید نکند.",
                verbose_name="نیاز به تکمیل دوره",
            ),
        ),
    ]
